---
version: '3.8'

volumes:
  grafana-data:
    driver: local
  influxdbv2:


services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  telegraf:
    image: toodaniels/telegraf-rocm
    devices:
      - /dev/dri/:/dev/dri/
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      #- ./rocm/bin/rocm-smi:/opt/rocm/bin/rocm-smi
    env_file:
      - influxv2.env
